### ISSUE TITLE
implement as a standalone Firefox application

### ISSUE THREAD

**Issue by ildar** [mindmup/mindmup#65]
.. and put it in https://marketplace.firefox.com/
I think that a standalone implementation for offline use may be quite interesting in any form (not just a FF app). But FF app seems quite natural for web-ish app.

**Comment by gojko** [comment]
if you want to propose new features, please use http://discover.mindmup.com

btw, there is a standalone chrome app https://chrome.google.com/webstore/detail/mindmup-desktop-free-mind/eealagocaipaflcjmeapmobpmilffopi that works offline

**Comment by ildar** [comment]
Thanks a lot! That is almost precisely what I meant, just for Chrome, not
FF.
