### ISSUE TITLE
Node size when text is long

### ISSUE THREAD

**Issue by gagou9** [mindmup/mindmup#66]
Hello!

I couldn't find a way to setup a node size, and it's especially anoying when the text in the node is a bit long! (I'm pre-writing a zine using freemind, and I'm trying to find a good replacement for my wisemapping instance. mindmup looks very great :) )

Please forgive me if I just missed it...

Thanks for this project anyway ! It really looks promising!

**Comment by gojko** [comment]
nodes are auto-sized. when you have a lot of text, it's best to put the huge chunk of text into an attachment, and leave the node just as a title or hint. See http://blog.mindmup.com/p/working-with-attachments.html

**Comment by gagou9** [comment]
Hi gojko !

When I tried using your demo, the size of the cell wouldn't grow!
And I don't really want to use attachments, as I'm using mindmapping to create a draft for a small book, and I need "global vision" :)
But whatever, I think I can handle it this way!

thanks!
