### ISSUE TITLE
Mindgraph?

### ISSUE THREAD

**Issue by thegreatmichael** [mindmup/mindmup#68]
Forgive me if this was sufficiently answered by https://github.com/mindmup/mindmup/issues/62#issuecomment-67849063, but sometimes when I am working on exploring a subject, especially if I'm learning something new or doing research, I know that different things might connect, but I don't know how yet. It would be really nice if there were a tool that allowed me to have separate graphs (maybe tress would suffice) that i can gradually build up and eventually tie together (basically mindmup only currently supports a deductive process which is more appropriate if i already have a decent understanding of the structure of the knowledge space, but an inductive process could be helpful when i don't). (Lazy guy didn't read source and asks:) Is the implementation of mindmup such that a multiple graphs or at least a forest would be a dramatic change?

**Comment by gojko** [comment]
not a dramatic change, but those things are not mindmaps. the purpose of mindmup is to allow people to quickly create and share simple mind maps. this is a common request, so if you add your vote to http://mindmup.uservoice.com, we might actually do it if it climbs to the top
