### ISSUE TITLE
I create it  in my local machine, the page is like this ,what't wrong?

### ISSUE THREAD

**Issue by aihuasxy** [mindmup/mindmup#69]
![wrong](https://cloud.githubusercontent.com/assets/6761242/7214812/b0542476-e5ee-11e4-856d-545b61ecdd0e.png)

**Comment by gojko** [comment]
you have most likely not configured where to go and fetch CDN resources (like external CSS and javascript)

**Comment by aihuasxy** [comment]
thx
where can find the external.js and external.css

**Comment by gojko** [comment]
check out this project: https://github.com/mindmup/static.mindmup.com

and run pack.sh - this will create the static files in the content folder. then you can push them to a CDN or serve from your server.
