### ISSUE TITLE
Node status update.

### ISSUE THREAD

**Issue by rakdosss** [mindmup/mindmup#72]
Hello guys. 

First of all, I am very grateful to all the developers who created MindMup. 

I have noticed something while using node statuses (e.g. Progress, Done, Parked etc.). Once all the child nodes have the same status, the parent status is recalculated, which is correct. BUT if I remove the only item that does not match with status, the parent status is not updated and it is necessary to either to it by hand or update a child node to the same status. Do you think it is possible to perform a status recalculation for a parent node once a child is appended of removed from it?

**Comment by gojko** [comment]
that's possible and it's been on our list for a while, but something always comes up as higher priority. I suggest you vote for it at http://mindmup.uservoice.com, that will make us do it sooner and you'll get a notification when the ticket is closed
