### ISSUE TITLE
Running standalone section in README.md outdated

### ISSUE THREAD

**Issue by viegelinsch** [mindmup/mindmup#74]
The section [Running standalone](../blob/master/README.md#running-standalone) in README.me is outdated since static files have been extracted to [static.mindmup.com](https://github.com/mindmup/static.mindmup.com) CDN.

I would appreciate an update very much.

Regards.

**Comment by gojko** [comment]
the files are in the staric.mindmup.com project on github. You can use pack.sh to create bundled versions. See https://github.com/mindmup/static.mindmup.com
