### ISSUE TITLE
Blank Nodes

### ISSUE THREAD

**Issue by megerbyte** [mindmup/mindmup#76]
I find that when I import a large map from a .mm file, some of the nodes are blank, in that the text from the original is not in the mindmup version.  Any suggestions as to a fix as going through these large maps looking for missing node information then searching back to the original is very time consuming, especially when the intent is to be constantly updating from the .mm file.

**Comment by megerbyte** [comment]
Update: It seems that the system takes the node text and puts it in as a note.  Curious!

**Comment by gojko** [comment]
the system takes HTML node text and puts it into an attachment, because mindmup nodes can't contain HTML, just text. Attachments can contain HTML. Freemind supports both textual and HTML nodes
