### ISSUE TITLE
Browserify seems to compile it wrong.

### ISSUE THREAD

**Issue by netAction** [mindmup/mindmup#79]
npm install mindmup-mapjs
    npm install browserify
    node ../node_modules/browserify/bin/cmd.js -r mindmup-mapjs > mapjs.js

Firefox throws exception: TypeError: $ is undefined mapjs.js:3807:5

The content of that line:

    $.fn.hammer = function(options) {

jQuery is included and starts at line 4041. Maybe the order of the dependencies is wrong?

**Comment by gojko** [comment]
check out readme from https://github.com/mindmup/mapjs to see how to browserify with all the dependencies
