### ISSUE TITLE
Mindmup 2.0 - Your changes are not yet saved...

### ISSUE THREAD

**Issue by jesuissur** [mindmup/mindmup#80]
Hi

I do some changes on a MindMup 2.0 file and all of a sudden, the changes stopped being saved.  The network works fine and every other things in Google drive are also doing ok.

I can't recover the changes unless I save as a Mindmup desktop file and import in an other MindMup Google drive file.

This is tme message I got
![image](https://cloud.githubusercontent.com/assets/136296/11747084/4b038358-9fef-11e5-85ec-9526cfbb0f1c.png)

Thanks
Phil

**Comment by gojko** [comment]
this is a message we get from google drive, so there's something preventing the changes from going through to them. have you installed any content blockers that would stop messages going to Drive (eg disconnect.me, an ad blocker or some kind of privacy protection extension?) sometimes those things kill more than they should, so you may need to whitelist google drive to make it work.

**Comment by jesuissur** [comment]
I got ad blocker, I'll try to deactivate for mindmup website and see how it is going.
Thanks

**Comment by jesuissur** [comment]
It seems to work fine now.  Maybe the tooltip could display this tip along the "check your network" one.
Thanks again
