### ISSUE TITLE
Mindmup local install not working properly

### ISSUE THREAD

**Issue by viclix10** [mindmup/mindmup#82]
I installed mindmup locally on my mac using
```
gem install foreman
bundle install
foreman start
```
But mindmup does not work/render properly (picture below). Any help/pointers will be useful. 

<img width="1395" alt="screen shot 2016-02-23 at 8 04 31 pm" src="https://cloud.githubusercontent.com/assets/8381296/13275444/130fe9fe-da6a-11e5-8ae2-5ee5f961185c.png">

**Comment by gojko** [comment]
this whole repository is horribly outdated, and will no longer be maintained actively. we're migrating to version 2.0 that's not on github yet.

**Comment by viclix10** [comment]
Do you have an ETA on github version of mindmup 2.0?

**Comment by gojko** [comment]
not at the moment, we're still building it up

**Comment by viclix10** [comment]
Sure. One last thing "Terrific Product"

**Comment by gojko** [comment]
thanks
