### ISSUE TITLE
GDrive can't open mindmup in my company

### ISSUE THREAD

**Issue by llgcode** [mindmup/mindmup#88]
I've created a mind map at home with mindmup 2. But when I try to open at work it failed.

![image](https://cloud.githubusercontent.com/assets/524083/17769628/d46ff6fc-6539-11e6-8cee-83af0812274b.png)

I 've created a new mind map at work and save it to drive as .mup extension it seems to work at my company but seem to be version 1 of mindmup.

**Comment by gojko** [comment]
Hi,

this isn't the right place to report operational stuff. if you have a Gold account, send an e-mail to support@mindmup.com. Without a Gold account, you'll have to troubleshoot the network problems yourself, we don't offer individual support to free users.
