### ISSUE TITLE
Connect items with Github issues?

### ISSUE THREAD

**Issue by atrandafir** [mindmup/mindmup#89]
Hello,

I was wondering did you think of the feature of somehow connecting the items with issues on Github to use it somehow to track progress of a project?

Thanks and sorry this is not a real issue!

**Comment by gojko** [comment]
you can paste a link to a github issue into a node. that's kind of the most we can do now.

**Comment by atrandafir** [comment]
thanks for the feedback, that could be enough to get going! :)
